file_name: Product.0.1.0.yaml
root:
  name: Product
  description: Products, SKUs, and items managed in the supply chain with specifications and attributes
  type: object
  properties:
  - name: _id
    description: The unique identifier for the Product.
    type: identifier
  - name: name
    description: The searchable name of the document
    type: word
  - name: description
    description: The description of the Product.
    type: sentence
  - name: created
    description: The tracking breadcrumb for when the document was created.
    type: breadcrumb
  - name: saved
    description: The tracking breadcrumb for when the document was last saved.
    type: breadcrumb
  - name: status
    description: Status of the document
    type: enum
    enums: default_status